image: "coqorg/coq:latest"

debug partition:
  stage: build

  artifacts:
    paths:
      - pip-edf-scheduler.bin
    expire_in: 1 hour

  script:
    # Get C and assembly compilers
    - .ci/apt-get.sh nasm gcc

    # Build the Libpip
    - git submodule init
    - git submodule update
    - make -C src/partition/lib/libpip
    
    # get digger from latest CI artifacts
    - cd tools/digger
    - curl -L 'https://gitlab.univ-lille.fr/2xs/digger/-/jobs/artifacts/master/download?job=build' -o digger.zip
    - unzip -o digger.zip
    - ./digger --version
    - cd ../..

    - make pip-edf-scheduler.bin
